[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "passform2"
version = "0.1.0"
description = "PassForM2 Applikation"
dependencies = [
    "fastapi",
    "uvicorn",
    "psutil",
    "websockets"
]

[tool.setuptools]Dependencies!"
packages = []