modules:
  # row 0
  - position: [0, 0]
    module_type: greifer
    is_goal: false
  - position: [0, 1]
    module_type: greifer
    is_goal: false
  - position: [0, 2]
    module_type: greifer
    is_goal: false
  - position: [0, 3]
    module_type: greifer
    is_goal: false
  - position: [0, 4]
    module_type: greifer
    is_goal: false
  - position: [0, 5]
    module_type: greifer
    is_goal: false
  - position: [0, 6]
    module_type: greifer
    is_goal: false
  - position: [0, 7]
    module_type: greifer
    is_goal: false
  - position: [0, 8]
    module_type: greifer
    is_goal: false
  - position: [0, 9]
    module_type: greifer
    is_goal: false

  # row 1
  - position: [1, 0]
    module_type: greifer
    is_goal: false
  - position: [1, 1]
    module_type: greifer
    is_goal: false
  - position: [1, 2]
    module_type: greifer
    is_goal: false
  - position: [1, 3]
    module_type: greifer
    is_goal: false
  - position: [1, 4]
    module_type: greifer
    is_goal: false
  - position: [1, 5]
    module_type: greifer
    is_goal: false
  - position: [1, 6]
    module_type: greifer
    is_goal: false
  - position: [1, 7]
    module_type: greifer
    is_goal: false
  - position: [1, 8]
    module_type: greifer
    is_goal: false
  - position: [1, 9]
    module_type: greifer
    is_goal: false

  # row 2
  - position: [2, 0]
    module_type: greifer
    is_goal: false
  - position: [2, 1]
    module_type: greifer
    is_goal: false
  - position: [2, 2]
    module_type: greifer
    is_goal: false
  - position: [2, 3]
    module_type: greifer
    is_goal: false
  - position: [2, 4]
    module_type: greifer
    is_goal: false
  - position: [2, 5]
    module_type: greifer
    is_goal: false
  - position: [2, 6]
    module_type: greifer
    is_goal: false
  - position: [2, 7]
    module_type: greifer
    is_goal: false
  - position: [2, 8]
    module_type: greifer
    is_goal: false
  - position: [2, 9]
    module_type: greifer
    is_goal: false

  # row 3
  - position: [3, 0]
    module_type: greifer
    is_goal: false
  - position: [3, 1]
    module_type: greifer
    is_goal: false
  - position: [3, 2]
    module_type: greifer
    is_goal: false
  - position: [3, 3]
    module_type: greifer
    is_goal: false
  - position: [3, 4]
    module_type: greifer
    is_goal: false
  - position: [3, 5]
    module_type: greifer
    is_goal: false
  - position: [3, 6]
    module_type: greifer
    is_goal: false
  - position: [3, 7]
    module_type: greifer
    is_goal: false
  - position: [3, 8]
    module_type: greifer
    is_goal: false
  - position: [3, 9]
    module_type: greifer
    is_goal: false

  # row 4
  - position: [4, 0]
    module_type: greifer
    is_goal: false
  - position: [4, 1]
    module_type: greifer
    is_goal: false
  - position: [4, 2]
    module_type: greifer
    is_goal: false
  - position: [4, 3]
    module_type: greifer
    is_goal: false
  - position: [4, 4]
    module_type: greifer
    is_goal: false
  - position: [4, 5]
    module_type: greifer
    is_goal: false
  - position: [4, 6]
    module_type: greifer
    is_goal: false
  - position: [4, 7]
    module_type: greifer
    is_goal: false
  - position: [4, 8]
    module_type: greifer
    is_goal: false
  - position: [4, 9]
    module_type: greifer
    is_goal: false

  # row 5
  - position: [5, 0]
    module_type: greifer
    is_goal: false
  - position: [5, 1]
    module_type: greifer
    is_goal: false
  - position: [5, 2]
    module_type: greifer
    is_goal: false
  - position: [5, 3]
    module_type: greifer
    is_goal: false
  - position: [5, 4]
    module_type: greifer
    is_goal: false
  - position: [5, 5]
    module_type: greifer
    is_goal: false
  - position: [5, 6]
    module_type: greifer
    is_goal: false
  - position: [5, 7]
    module_type: greifer
    is_goal: false
  - position: [5, 8]
    module_type: greifer
    is_goal: false
  - position: [5, 9]
    module_type: greifer
    is_goal: false

  # row 6
  - position: [6, 0]
    module_type: greifer
    is_goal: false
  - position: [6, 1]
    module_type: greifer
    is_goal: false
  - position: [6, 2]
    module_type: greifer
    is_goal: false
  - position: [6, 3]
    module_type: greifer
    is_goal: false
  - position: [6, 4]
    module_type: greifer
    is_goal: false
  - position: [6, 5]
    module_type: greifer
    is_goal: false
  - position: [6, 6]
    module_type: greifer
    is_goal: false
  - position: [6, 7]
    module_type: greifer
    is_goal: false
  - position: [6, 8]
    module_type: greifer
    is_goal: false
  - position: [6, 9]
    module_type: greifer
    is_goal: false

  # row 7
  - position: [7, 0]
    module_type: greifer
    is_goal: false
  - position: [7, 1]
    module_type: greifer
    is_goal: false
  - position: [7, 2]
    module_type: greifer
    is_goal: false
  - position: [7, 3]
    module_type: greifer
    is_goal: false
  - position: [7, 4]
    module_type: greifer
    is_goal: false
  - position: [7, 5]
    module_type: greifer
    is_goal: false
  - position: [7, 6]
    module_type: greifer
    is_goal: false
  - position: [7, 7]
    module_type: greifer
    is_goal: false
  - position: [7, 8]
    module_type: greifer
    is_goal: false
  - position: [7, 9]
    module_type: greifer
    is_goal: false

  # row 8
  - position: [8, 0]
    module_type: greifer
    is_goal: false
  - position: [8, 1]
    module_type: greifer
    is_goal: false
  - position: [8, 2]
    module_type: greifer
    is_goal: false
  - position: [8, 3]
    module_type: greifer
    is_goal: false
  - position: [8, 4]
    module_type: greifer
    is_goal: false
  - position: [8, 5]
    module_type: greifer
    is_goal: false
  - position: [8, 6]
    module_type: greifer
    is_goal: false
  - position: [8, 7]
    module_type: greifer
    is_goal: false
  - position: [8, 8]
    module_type: greifer
    is_goal: false
  - position: [8, 9]
    module_type: greifer
    is_goal: false

  # row 9
  - position: [9, 0]
    module_type: greifer
    is_goal: false
  - position: [9, 1]
    module_type: greifer
    is_goal: false
  - position: [9, 2]
    module_type: greifer
    is_goal: false
  - position: [9, 3]
    module_type: greifer
    is_goal: false
  - position: [9, 4]
    module_type: greifer
    is_goal: false
  - position: [9, 5]
    module_type: greifer
    is_goal: false
  - position: [9, 6]
    module_type: greifer
    is_goal: false
  - position: [9, 7]
    module_type: greifer
    is_goal: false
  - position: [9, 8]
    module_type: greifer
    is_goal: false
  - position: [9, 9]
    module_type: greifer
    is_goal: false
