rpi_i2c_di:
  ros__parameters:
    address: 0x38
    period: 1
    length: 8
    topic: "di_data"

rpi_i2c_do:
  ros__parameters:
    address: 0x20
    period: 1
    length: 8
    values: 1
    topic: "do_data"

rpi_i2c_ai:
  ros__parameters:
    address: 0x08
    period: 1
    length: 5
    topic: "ai_data"

rpi_i2c_ao:
  ros__parameters:
    address: 0x58
    period: 1
    length: 4
    topic: "ao_data"

# rpi_gpio_us:
#   ros__parameters:
#     period: 1
#     trigger_GPIO_1: 20
#     echo_GPIO_1: 21
#     trigger_GPIO_2: 19
#     echo_GPIO_2: 26
#     topic: "us_data"

# modul_logic:
#   ros__parameters:
#     period: 1
#     publisher_topic: "ao_data"
#     topic_di: "di_data"
#     topic_ai: "ai_data"
#     topic_us: "us_data"

  # angle_sensor:
  #   ros__parameters:
  #     joint_name: jointtest
  #     topic_ai: ai_data
