1:
  xyz: [0.88015, -0.0776, 0.89625]
  rpy: [0, 0, 4.7123889]
2:
  xyz: [0.28515, -0.0776, 0.89625]
  rpy: [0, 0, 4.7123889]
3:
  xyz: [-0.30985, -0.0776, 0.89625]
  rpy: [0, 0, 4.7123889]
4:
  xyz: [-0.90485, -0.0776, 0.89625]
  rpy: [0, 0, 4.7123889]
5:
  xyz: [0.90485, 0.0776, 0.89625]
  rpy: [0, 0, 1.5707963]
6:
  xyz: [0.30985, 0.0776, 0.89625]
  rpy: [0, 0, 1.5707963]
7:
  xyz: [-0.28515, 0.0776, 0.89625]
  rpy: [0, 0, 1.5707963]
8:
  xyz: [-0.88015, 0.0776, 0.89625]
  rpy: [0, 0, 1.5707963]